### ISSUE TITLE
Feature: Busca de condomino

### ISSUE THREAD

**Issue by TayaneCibely** [CondoMine/CondoMine#43]
Feature: Busca de condomino
As a Usuario do sistema
I want to buscar condominos informando nome ou CPF
So that eu visualize o cadastro completo do condomino desejado

**Comment by Dev-LucasMelo** [comment]
unica parte pendente são os testes referentes ao filtro, vou repassar para @andrewlopes11 para a gente analisar os scenarios e seguir para a implementação
